load("@bazel_skylib//lib:selects.bzl", "selects")

package(default_visibility = ["//visibility:public"])

selects.config_setting_group(
    name = "is_cross_compiler",
    match_any = [
        "//constraints/is_systemcore:systemcore",
        "//constraints/is_systemcore_debug:systemcore_debug",
        "//constraints/is_trixie64:trixie64",
    ],
)

selects.config_setting_group(
    name = "is_unix",
    match_any = [
        "@platforms//os:macos",
        "@platforms//os:linux",
    ],
)

selects.config_setting_group(
    name = "is_linux",
    match_any = [
        "@platforms//os:linux",
    ],
)
