workspace(name = "rules_bzlmodrio_toolchains-gentool")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Python, for gentool
http_archive(
    name = "rules_python",
    sha256 = "0a8003b044294d7840ac7d9d73eef05d6ceb682d7516781a4ec62eeb34702578",
    strip_prefix = "rules_python-0.16.1",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.16.1/rules_python-0.16.1.tar.gz",
)

local_repository(
    name = "bzlmodrio-gentool",
    path = "../../../gentool",
)

load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "bzlmodrio-gentool-pip",
    requirements_lock = "@bzlmodrio-gentool//:requirements_lock.txt",
)

load("@bzlmodrio-gentool-pip//:requirements.bzl", "install_deps")

install_deps()
