name: Publish Module
on:
  workflow_dispatch:
  push:
    tags:
    - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  publish_module:
    name: "Publish Module"
    runs-on: ubuntu-22.04
    steps:
    # Checkout repository
    - uses: actions/checkout@v4
      with:
        path: rules/wpilib_toolchains

    - name: Create Archive
      run: git archive HEAD --format=tar.gz --output="wpilib_toolchains-${GITHUB_REF_NAME}.tar.gz"
      working-directory: rules/wpilib_toolchains

    - name: Setup archive name
      run: echo "ARCHIVE_NAME=rules/wpilib_toolchains/wpilib_toolchains-${GITHUB_REF_NAME}.tar.gz" >> "$GITHUB_ENV"

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "${{ env.ARCHIVE_NAME }}"

  publish-bcr:
    name: "Publish to BCR"
    needs: publish_module
    if: startsWith(github.ref, 'refs/tags/')
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v1.2.0
    with:
      tag_name: ${{ github.ref_name }}
      registry_fork: wpilibsuite/bazel-central-registry
    secrets:
      publish_token: ${{ secrets.PUBLISH_TOKEN }}
